version: '3.9'

services:
  qdrant: 
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/data

  redis:
    image: redis
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: celery -A app worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - TELEGRAM_API=${TELEGRAM_API}
      - OPENAI_API=${OPENAI_API_KEY}
      - PYTHONPATH=/app

    depends_on:
      - redis

  telegram_bot:
    build: .
    env_file:
      - .env  
    environment:
      - TELEGRAM_API=${TELEGRAM_API}
      - OPENAI_API=${OPENAI_API_KEY}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - PYTHONPATH=/app

    depends_on:
      - redis
      - celery_worker
